info:
  name: create-task
  type: http
  seq: 2

http:
  method: POST
  url: http://localhost:5000/api/tasks
  body:
    type: json
    data: |-
      {
        "title": "New task 2",
        "description": "Task description here"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
