info:
  name: remove-task
  type: http
  seq: 4

http:
  method: DELETE
  url: http://localhost:5000/api/tasks/:id
  params:
    - name: id
      value: 5d117498-8c10-4107-b236-407425164f01
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
