info:
  name: update-task
  type: http
  seq: 3

http:
  method: PATCH
  url: http://localhost:5000/api/tasks/:id
  params:
    - name: id
      value: 2d88545d-a262-4ac2-bdf8-19dfab08152b
      type: path
  body:
    type: json
    data: |-
      {
        "title": "Updated task",
        "description": "Updated description",
        "isDone": false,
        "isPinned": false
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
